Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list data type, while array_list is a numpy array data type.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing data type of each element in list_
for element in list_:
    print("Data type of element in list_:", type(element))

# Printing data type of each element in array_list
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int) 
Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list. 

Yes, there will be a difference in the data type of the elements present in both list_ and array_list when dtype is set to int. In this case, the strings in list_ will be converted to integer data type in array_list

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Printing data type of each element in list_
for element in list_:
    print("Data type of element in list_:", type(element))

# Printing data type of each element in array_list
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


Consider the below code to answer further questions: 
import numpy as np 
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
import numpy as np 

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Finding the shape and size of the num_array
shape = num_array.shape
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array.
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
import numpy as np

# Creating a numpy array of 3x3 with zeros only
zeros_array = np.zeros(shape=(3, 3))

print("Zeros array:\n", zeros_array)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [9]:
import numpy as np

# Creating an identity matrix of shape (5,5)
identity_matrix = np.identity(n=5)

print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
